version: '3.6'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPassword
      POSTGRES_DB: database

  server:
    image: node
    ports:
      - 5000:3000
    volumes:
      - ./backend:/usr/node/app
    working_dir: /usr/node/app
    environment:
      DATABASE_URL: postgres://pgUser:pgPassword@db:5432/database
      JWT_SECRET: ImAstrongSecret
      MONGO_URI: mongodb://root:password@mongo/app
    command: "sh -c 'npm install && npm run server'"
   