version: '3.6'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPassword
      POSTGRES_DB: database

  server:
    image: node
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://root:password@db:5432/app
      JWT_SECRET: ImAstrongSecret
